@url=http://localhost:3001/api/users

@json=Content-Type: application/json
###
get {{url}}
###
post {{url}}/register
{{json}}

{
    "username": "user1",
    "password": "123456",
    "email": "abc"
}
###
post {{url}}/login
{{json}}

{
    "username": "user1",
    "password": "123456",
    "email": "abc"
}
###
get {{url}}/62721d3184b1b01aab791df5/username
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzIyMjYxNWRmYTYwYjEyOTBkMjJhMyIsImlhdCI6MTY1MTY0NzA4NX0.FtduWKimzUyKbQPz8BZqvNJ6uFjEnBnosrmu-2SZw2A